nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome..')
print(f'Seu nome em maiusculo é {nome.upper()}')
print(f'Seu nome em minusculo é {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(' ')} letras')